name = "DataFrameGates"
uuid = "9b2ceffa-7062-4978-ab82-60af2f483a2b"
authors = ["Beno√Æt Richard <kolaru@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"

[compat]
DataFrames = "1.8.1"
Intervals = "1.10.0"
MacroTools = "0.5.16"
Memoization = "0.2.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
